# nonk8s
apiVersion: test/v1-alpha
kind: TestStep
metadata:
  name: partner-creates-client
spec:
  post: ${credits}/partners/${partnerID}/clients
  headers:
    Api-Key: ${partnerApiKey}
  body:
    externalId: "${externalId:random.regex:/^[a-zA-Z]{3}-[a-zA-Z0-9]{3}-[0-9]{6}$/}"
    creditLine:
      amount: "5000.00"
      currency: "MXN"
    legalName: ${companyName:random.companyName}
    dba: ${dba:random.companyName}
    taxId: ${taxId:random.regex:/[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/}
    phone: ${phone:random.phone}
    email: ${email:random.email}
    address: ${address:random.address}

  response:
    statusCode: 200
    body:
      address: $address
      cmsClientId": 0
      dba: $dba
      emailAddress: $email
      enabled: true
      externalId: $externalId
      id: $(clientID)
      isEmailVerified: false
      isPhoneVerified: false
      legalName: $legalName
      partnerId: $partnerID
      phoneNumber: $phone
      taxId: $taxId
